### ISSUE TITLE
Can't load comment for the last 12 hours

### ISSUE THREAD

**Issue by hafizhmakmur** [SimonHalvdansson/Harmonic-HN#122]
Right now every post in the last 12 hours (or even more) doesn't have any comments and have "Loading Failed" instead. 

![Screenshot_20231107_174102_Harmonic](https://github.com/SimonHalvdansson/Harmonic-HN/assets/14178101/0e50bae9-e20f-46a3-96b3-145d8790e65d)

**Comment by trySometngNew** [comment]
Hi @SimonHalvdansson,
I came here to post this exact issue. I am also unable to load recent hn posts  comments. Tried deleting data, reinstalling app, nothing seems to work.



Regards, 
Sourabh

**Comment by SimonHalvdansson** [comment]
This is due to the HN Algolia API being down. Long term I want to enable an alternate API backend but for now I've set a nice error message when this happens in https://github.com/SimonHalvdansson/Harmonic-HN/commit/f373225216eb28ea8bfacbecd8f300098d9baa43. As a user, there is nothing that can be done right now but these things usually pass in not too long.

**Comment by hafizhmakmur** [comment]
Ah so it's algolia. I forgot what HN API was and only found firebase when I google it so I thought it's not an API problem. I hope it'll not last too long.
