### ISSUE TITLE
Collapsing comment with a lot of children causes lag

### ISSUE THREAD

**Issue by AppearamidGuy** [SimonHalvdansson/Harmonic-HN#87]
For example recent story about iPhone 15 has a comment with 269 responses: https://news.ycombinator.com/item?id=37485290
Collapsing this comment and scrolling past it is laggy.

The reason is collapsed comments are implemented as recyclerview items with zero height. So the recycler has to inflate all hundreds of hidden comments just to never show them every time user scroll past them. The correct solution is to completely skip hidden comments in `CommentsRecyclerViewAdapter`

**Comment by SimonHalvdansson** [comment]
This is very true - I have been thinking that the inflation is not too bad since there's very little code in the onBindViewHolder being run but the inflation is probaly what is killing performance here. What's the best way to treat this, to have a body double of the `comments` ArrayList which is always full and then remove and add elements to the ArrayList in the adapter?

**Comment by AppearamidGuy** [comment]
> What's the best way to treat this, to have a body double of the comments ArrayList which is always full and then remove and add elements to the ArrayList in the adapter?

Yes, I can't come up with anything better than this

>  the best way

Oh... So first you need to select a Single Source of Truth. Your UI will always display what's in this SSoT. Also you need to be offline-first, so SSoT is a DB accessed via Room. But of course you also need to get data from network, so you need a `Repository`. And because you now have two sources of data, you need a `Mediator`. Now we can finally display the data, but you can't access `Mediator` from `Adapter` or even `Fragment`, you need a `ViewModel`. Also calling `notifyItemRange*` on `Adapter` is too difficult, you need to use `ListAdapter`. Yay, we're halfway there and click handling is easy, just do everything in reverse: `ListAdapter` -> `Fragment` -> `ViewModel` -> `UseCase` -> `Mediator` -> `DB`/`Repository`. Did you notice that there's a `UseCase` here? You actually need it for displaying data too, I just skipped it for simplicity. Also all these objects can't just construct each other, you need to use DI framework like Dagger or even better - Hilt. But actually since you are writing in Kotlin the best framework is Koin. Wait, what do you mean you don't use Kotlin? Then forget it, it won't be good anyways \s

**Comment by yigit** [comment]
I actually took a look at this (i'm one of the original authors of RecyclerView).
As much as the previous comment is a sarcasm, it does have some truth. Ideally, what you want in this situation is to remove those items from the adapter but that is really hard to implement when so many parts of the code edit the comments list and its instances. Ideally, you want everything shown by the RecyclerView stay immutable. And if it was implemented that way, you can get rid of all the scroll recovery etc logic because RecyclerView would do that for you.

You don't need all the pieces mentioned above but what you really need is a model for your comments list that handles all modifications and then just update the adapter via something like AsyncDiffUtil (which will also allow you to get rid of all custom notify item changed logic).

Now, there is also "**if it works, don't break it**" and your app certainly works (happy user here).

So assuming you don't have appetite to rearchitect this part to isolate all comment data management, a possible improvement is to not inflate your real view for this collapsed items. Instead, create a ViewHolder with a code initiated View with 0 height, and return that from `getItemViewType` / `onCreateViewHolder`. You may also want to increase the item cache size in the recycler so that these views don't churn. 
Note that, the View class itself is already big (In memory) so this won't be a perfect solution but a reasonable improvement.

Also, RecyclerView really goes bananas with 0 height views so getting rid of them would be ideal but that is a big refactor.

**Comment by SimonHalvdansson** [comment]
I really appreciate you looking into this! And what's been said about proper data structures is very true but it is also very true that I don't have too much of an appetite to rearchitecture things. I implemented the improvement you outlined and I can now scroll through ~1500 comments with no lag so I consider this to be fixed so thank you so much for helping out! :)

Hopefully this should bring with it reduced memory usage even though it is not optimal and also there is no visible going bananas with the zero height code initialized empty view so good work on RecyclerView for keeping that under wraps :)
